install.packages('ggplot2')
install.packages("dplyr")
install.packages("rattle.data")
install.packages("magrittr")
install.packages("readr")
install.packages("FSelector")
install.packages("lubridate")
install.packages("randomForest")
install.packages("readr")
install.packages("scales")
install.packages("stringi")
install.packages("stringr")
install.packages("tibble")
install.packages("curl")

